DROP TABLE VATMAST;

CREATE TABLE VATMAST
	(
	IDNO     INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE),
	FRMDATE DATE NOT NULL,
	TODATE  DATE NOT NULL,
	VATRT   DECIMAL (6,2) DEFAULT 0
	);

