UPDATE MAINMENU
SET ACTIVE = 'N'
WHERE MENUCODE = 'SET002';

UPDATE MAINMENU
SET ACTIVE = 'N'
WHERE MENUCODE = 'SET003';

UPDATE MAINMENU
SET ACTIVE = 'N'
WHERE MENUCODE = 'SET406';

UPDATE MAINMENU
SET ACTIVE = 'N'
WHERE MENUCODE = 'SET407';

UPDATE MAINMENU
SET ACTIVE = 'N'
WHERE MENUCODE = 'SET408';

UPDATE MAINMENU
SET ACTIVE = 'N'
WHERE MENUCODE = 'SET411';

UPDATE MAINMENU
SET ACTIVE = 'N'
WHERE MENUCODE = 'SET708';

UPDATE MAINMENU
SET ACTIVE = 'N'
WHERE MENUCODE = 'SET709';