DROP TRIGGER AFTINS_PASSWRD;

CREATE TRIGGER AFTINS_PASSWRD
AFTER INSERT ON PASSWRD REFERENCING
NEW AS N FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC
      INSERT INTO MENUSYSTRAN(USERID,MAINMENU,TRANMENU,MENUGROUP,TRANGROUP,
                              MENUCODE,MENUDESC,M_ACCESS,M_EDIT,M_INSERT,M_DELETE)
      SELECT B.USERID,A.MAINMENU,A.TRANMENU,A.MENUGROUP,A.TRANGROUP,
             A.MENUCODE,A.MENUDESC,'Y','Y','Y','Y' 
             FROM MENUSYS A,PASSWRD B
             WHERE B.USERID=N.USERID;
             
		INSERT INTO USERMENU (USERID, MENUCODE)
	    SELECT B.USERID, A.MENUCODE
	    FROM MAINMENU A,PASSWRD B
	    WHERE B.USERID = N.USERID;             
END;
