ALTER TABLE CHQMAS ADD CONTNO CHARACTER(20) DEFAULT '';
ALTER TABLE CHQMAS ADD TSALE CHARACTER(1) DEFAULT '';
ALTER TABLE PAYFOR ADD SALETYPE CHARACTER(1) DEFAULT '';

UPDATE CHQMAS SET CONTNO = (SELECT CONTNO FROM CHQTRAN WHERE CHQMASID = CHQMAS.IDNO GROUP BY CONTNO FETCH FIRST 1 ROWS ONLY);
UPDATE CHQMAS SET TSALE = (SELECT TSALE FROM CHQTRAN WHERE CHQMASID = CHQMAS.IDNO GROUP BY TSALE FETCH FIRST 1 ROWS ONLY);