ALTER TABLE CHQMAS ADD CONTNO CHARACTER(20) DEFAULT '';
ALTER TABLE CHQMAS ADD TSALE CHARACTER(1) DEFAULT '';

UPDATE CHQMAS SET CONTNO = (SELECT CONTNO FROM CHQTRAN WHERE CHQMASID = CHQMAS.IDNO GROUP BY CONTNO) WHERE FLAG <> 'C';
UPDATE CHQMAS SET TSALE = (SELECT TSALE FROM CHQTRAN WHERE CHQMASID = CHQMAS.IDNO GROUP BY TSALE FETCH FIRST 1 ROWS ONLY) WHERE FLAG <> 'C';