CREATE TABLE SETFLEET2 LIKE SETFLEET;
INSERT INTO SETFLEET2 SELECT * FROM SETFLEET;
DROP TABLE SETFLEET;

CREATE TABLE SETFLEET
	(
	IDNO     INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE),
	FLEETCOD VARCHAR (25) NOT NULL,
	FLEETNAM VARCHAR (100),
	CONSTRAINT PK_SETFLEET PRIMARY KEY (IDNO)
	);

INSERT INTO SETFLEET(FLEETCOD,FLEETNAM) SELECT * FROM SETFLEET2;