DROP TABLE CHQTYPE;

CREATE TABLE CHQTYPE
	(
	IDNO      INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE ),
	CHQMASID  INTEGER NOT NULL,
	PAYCODE   CHARACTER (5) NOT NULL,
	REFNO     VARCHAR (20) DEFAULT '',
	STATUS    CHARACTER (1) DEFAULT 'Y',
	AMOUNT    DECIMAL (12,2) DEFAULT 0,
	FLAG      CHARACTER (1) DEFAULT 'H',
	INPUTDT   TIMESTAMP,
	USERID    CHARACTER (8),
	CANDT     TIMESTAMP,
	CANUSERID CHARACTER (8),
	CONSTRAINT PRIMARY_IDNO PRIMARY KEY (IDNO)
	);


DROP TRIGGER AFTINS_CHQTYP_RSV;

CREATE TRIGGER AFTINS_CHQTYP_RSV
AFTER INSERT ON CHQTYPE REFERENCING NEW AS N FOR EACH ROW MODE DB2SQL
WHEN ( N.PAYCODE='00')
BEGIN ATOMIC
  UPDATE ARRESV SET CHQMAS=CHQMAS+N.AMOUNT  WHERE RESVNO=N.REFNO;
END;

DROP TRIGGER AFTINS_CHQTYPE;

CREATE TRIGGER AFTINS_CHQTYPE
AFTER INSERT ON CHQTYPE REFERENCING NEW AS N FOR EACH ROW MODE DB2SQL
WHEN ( N.PAYCODE='02')
BEGIN ATOMIC
  UPDATE CHQSTAT SET CHQPAY=CHQPAY+N.AMOUNT  WHERE CHQNO=N.REFNO;
END;

DROP TRIGGER AFTUPD_CHQTYP_RSV;

CREATE TRIGGER AFTUPD_CHQTYP_RSV
AFTER UPDATE OF FLAG ON CHQTYPE REFERENCING OLD AS O NEW AS N FOR EACH ROW MODE DB2SQL
WHEN ( O.PAYCODE='00')
BEGIN ATOMIC
   UPDATE ARRESV  SET CHQMAS=CHQMAS-O.AMOUNT  WHERE RESVNO=O.REFNO  AND N.FLAG='C';
END;

DROP TRIGGER AFTUPD_CHQTYPE;

CREATE TRIGGER AFTUPD_CHQTYPE
AFTER UPDATE OF FLAG ON CHQTYPE REFERENCING OLD AS O NEW AS N FOR EACH ROW MODE DB2SQL
WHEN ( O.PAYCODE='02')
BEGIN ATOMIC
  UPDATE CHQSTAT  SET CHQPAY=CHQPAY-O.AMOUNT  WHERE CHQNO=O.REFNO  AND N.FLAG='C';
END;
