INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET000', 'กำหนดข้อมูลระบบ', 1, 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK000', 'ระบบสต็อกสินค้า', 1, 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL000', 'ระบบการขายสินค้า', 1, 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, ACTIVE, SORT)
VALUES ('DMSPlus', 'FIN000', 'ระบบการรับชำระ', 1, 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, ACTIVE, SORT)
VALUES ('DMSPlus', 'AR000', 'ระบบลูกหนี้', 1, 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, ACTIVE, SORT)
VALUES ('DMSPlus', 'ADMIN000', 'ระบบความปลอดภัย', 1, 'Y', 6);

/* กำหนดข้อมูลระบบ  Level 2*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET001', 'กำหนดรายละเอียดสินค้า', 2, 'SET000', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET002', 'กำหนดแคมเปญ', 2, 'SET000', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET003', 'กำหนดแคมเปญกิจกรรมสนับสนุน', 2, 'SET000', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET004', 'กำหนดข้อมูลลูกหนี้', 2, 'SET000', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET005', 'กำหนดข้อมูลระบบการเงิน', 2, 'SET000', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET006', 'กำหนดข้อมูลบริษัทที่ติดต่อ', 2, 'SET000', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET007', 'กำหนดข้อมูลเบื้องต้นของระบบ', 2, 'SET000', 'Y', 7);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET008', 'กำหนดข้อมูล Data Center', 2, 'SET000', 'Y', 8);

/* กำหนดรายละเอียดสินค้า  Level 3*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET101', 'กำหนดยี่ห้อสินค้า', 3, 'SET001', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET102', 'กำหนดรุ่นสินค้า', 3, 'SET001', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET103', 'กำหนดแบบสินค้า', 3, 'SET001', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET104', 'กำหนดสีสินค้า', 3, 'SET001', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET105', 'กำหนดกลุ่มสินค้า', 3, 'SET001', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET106', 'กำหนดสถานะทางทะเบียน', 3, 'SET001', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET107', 'กำหนดรหัสอุปกรณ์เสริม', 3, 'SET001', 'Y', 7);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET108', 'กำหนดรหัสอุปกรณ์เสริมสาขา', 3, 'SET001', 'Y', 8);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET109', 'กำหนดอุปกรณ์ตกแต่ง', 3, 'SET001', 'Y', 9);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET110', 'กำหนดชุดแต่ง', 3, 'SET001', 'Y', 10);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET111', 'กำหนดรหัส Fleet', 3, 'SET001', 'Y', 11);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET112', 'กำหนดสถานะ Booking', 3, 'SET001', 'Y', 12);

/* กำหนดข้อมูลลูกหนี้  Level 3*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET401', 'กำหนดสถานะสัญญา', 3, 'SET004', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET402', 'กำหนดสาเหตุการยึด', 3, 'SET004', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET403', 'กำหนดสาเหตุหนี้สูญ', 3, 'SET004', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET404', 'กำหนดกลุ่มลูกหนี้', 3, 'SET004', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET405', 'กำหนดกลุ่มอาชีพลูกหนี้', 3, 'SET004', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET406', 'กำหนดอาชีพลูกนี้', 3, 'SET004', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET407', 'กำหนดแหล่งที่มาลูกค้า', 3, 'SET004', 'Y', 7);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET408', 'กำหนดรหัสตำบล', 3, 'SET004', 'Y', 8);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET409', 'กำหนดรหัสอำเภอ', 3, 'SET004', 'Y', 9);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET410', 'กำหนดรหัสจังหวัด', 3, 'SET004', 'Y', 10);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET411', 'กำหนดรหัสไปรษณีย์', 3, 'SET004', 'Y', 11);

/* กำหนดข้อมูลระบบการเงิน  Level 3*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET501', 'กำหนดประเภทการชำระเงิน', 3, 'SET005', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET502', 'กำหนดรหัสการรับชำระเงิน', 3, 'SET005', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET503', 'กำหนดรหัสธนาคาร', 3, 'SET005', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET504', 'กำหนดเลขที่บัญชีธนาคาร', 3, 'SET005', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET505', 'กำหนดสาเหตุการคืนเช็ค', 3, 'SET005', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET506', 'กำหนดวิธีการชำระเงิน', 3, 'SET005', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET507', 'กำหนดกิจกรรมการขาย', 3, 'SET005', 'Y', 7);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET508', 'กำหนดรหัสสาเหตุการลหนี้', 3, 'SET005', 'Y', 8);

/* กำหนดข้อมูลบริษัทที่ติดต่อ  Level 3*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET601', 'กำหนดบริษัทไฟแนนซ์', 3, 'SET006', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET602', 'กำหนดบริษัทประกันภัย', 3, 'SET006', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET603', 'กำหนดบริษัทเจ้าหนี้', 3, 'SET006', 'Y', 3);

/* กำหนดข้อมูลเบื้องต้นของระบบ  Level 3*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET701', 'กำหนดค่าคงที่ระบบ', 3, 'SET007', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET702', 'กำหนดข้อมูลสาขา', 3, 'SET007', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET703', 'กำหนดข้อมูลสถานที่จอด', 3, 'SET007', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET704', 'กำหนดหมวดหมู่เอกสาร', 3, 'SET007', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET705', 'กำหนดรหัสพนักงาน', 3, 'SET007', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET706', 'กำหนดรหัสแผนก', 3, 'SET007', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET707', 'กำหนดอัตราภาษี', 3, 'SET007', 'Y', 7);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET708', 'กำหนดส่วนลดปิดบัญชี', 3, 'SET007', 'Y', 8);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET709', 'กำหนดอัตราเบี้ยปรับ MRR', 3, 'SET007', 'Y', 9);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET710', 'กำหนด Running เอกสาร', 3, 'SET007', 'Y', 10);

/* กำหนดข้อมูล Data Center  Level 3*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET801', 'กำหนดช่องทางที่สะดวกติดต่อ', 3, 'SET008', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET802', 'กำหนดหัวข้อการโทรติดต่อ', 3, 'SET008', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SET803', 'กำหนดสถานะการติดต่อ', 3, 'SET008', 'Y', 3);

/* ระบบสต็อกสินค้า Level 2*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK001', 'โหลดข้อมูลสต็อกจาก DDMS', 2, 'STK000', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK002', 'บันทึกรับสินค้าเข้าสต็อก', 2, 'STK000', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK003', 'บันทึกรับอุปกรณ์เสริมเข้าสต็อก', 2, 'STK000', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK004', 'บันทึกรับอุปกรณ์ตกแต่ง', 2, 'STK000', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK005', 'ปรับปรุงสินค้าเข้าสต็อก', 2, 'STK000', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK006', 'บันทึกโอนย้ายสินค้าระหว่างสาขา', 2, 'STK000', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK007', 'บันทึกโอนย้ายรถเป็นสินทรัพย์', 2, 'STK000', 'Y', 7);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK008', 'บันทึกสถานที่จอดรถ', 2, 'STK000', 'Y', 8);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK009', 'สอบถามอุปกรณ์เสริมคงเหลือ', 2, 'STK000', 'Y', 9);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK010', 'สอบถามสินค้าคงเหลือ ณ วันที่', 2, 'STK000', 'Y', 10);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'STK011', 'สอบถามรายละเอียดสินค้า', 2, 'STK000', 'Y', 11);

/* ระบบการขายสินค้า Level 2*/
INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL001', 'บันทึกประวัติลูกค้าคาดหวัง', 2, 'SAL000', 'Y', 1);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL002', 'บันทึกประวัติลูกค้า/ผู้ค้ำประกัน', 2, 'SAL000', 'Y', 2);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL003', 'บันทึกข้อมูล A-Card', 2, 'SAL000', 'Y', 3);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL004', 'บันทึกการจองสินค้า', 2, 'SAL000', 'Y', 4);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL005', 'บันทึกระบุเลขตัวถัง Matching', 2, 'SAL000', 'Y', 5);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL006', 'บันทึกข้อมูลขายสินค้าเงินสด', 2, 'SAL000', 'Y', 6);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL007', 'บันทึกข้อมูลขายผ่อนเช่าซื้อ', 2, 'SAL000', 'Y', 7);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL008', 'บันทึกข้อมูลขายส่งไฟแนนซ์', 2, 'SAL000', 'Y', 8);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL009', 'บันทึกข้อมูลขายส่งเอเยนต์', 2, 'SAL000', 'Y', 9);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL010', 'บันทึกสรุปค่ารถจากบริษัทเงินทุน', 2, 'SAL000', 'Y', 10);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL011', 'บันทึกต้นทุนการขายรถ', 2, 'SAL000', 'Y', 11);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL012', 'สอบถามประวัติลูกค้า', 2, 'SAL000', 'Y', 12);

INSERT INTO MAINMENU (SYSTEMCOD, MENUCODE, MENUNAME, LEVAL, MENUGRP, ACTIVE, SORT)
VALUES ('DMSPlus', 'SAL013', 'สอบถามข้อมูลการขายรถ', 2, 'SAL000', 'Y', 13);
