UPDATE PAYFOR
SET SALETYPE = 'C'
WHERE FORCODE = '001';

UPDATE PAYFOR
SET SALETYPE = 'H'
WHERE FORCODE = '002';

UPDATE PAYFOR
SET SALETYPE = 'F'
WHERE FORCODE = '003';

UPDATE PAYFOR
SET SALETYPE = 'F'
WHERE FORCODE = '004';

UPDATE PAYFOR
SET SALETYPE = 'O'
WHERE FORCODE = '005';

UPDATE PAYFOR
SET SALETYPE = 'H'
WHERE FORCODE = '006';

UPDATE PAYFOR
SET SALETYPE = 'H'
WHERE FORCODE = '007';

UPDATE PAYFOR
SET SALETYPE = 'R'
WHERE FORCODE = '008';

UPDATE PAYFOR
SET SALETYPE = 'A'
WHERE FORCODE = '009';

UPDATE PAYFOR
SET SALETYPE = 'H'
WHERE FORCODE = '010';

UPDATE PAYFOR
SET SALETYPE = 'T'
WHERE FORCODE = '011';

UPDATE PAYFOR
SET SALETYPE = 'T'
WHERE FORCODE = '017';

UPDATE PAYFOR
SET SALETYPE = 'T'
WHERE FORCODE = '020';

UPDATE PAYFOR
SET SALETYPE = 'T'
WHERE FORCODE = '109';

UPDATE PAYFOR
SET SALETYPE = 'T'
WHERE FORCODE = '199';

UPDATE PAYFOR
SET SALETYPE = 'T'
WHERE FORCODE = '200';

UPDATE PAYFOR
SET SALETYPE = 'T'
WHERE FORCODE = '201';

UPDATE PAYFOR
SET SALETYPE = 'T'
WHERE FORCODE = '202';

UPDATE PAYFOR
SET SALETYPE = 'T'
WHERE FORCODE = '204';

UPDATE PAYFOR
SET SALETYPE = 'T'
WHERE FORCODE = '205';

UPDATE PAYFOR
SET SALETYPE = 'T'
WHERE FORCODE = '206';

UPDATE PAYFOR
SET SALETYPE = 'T'
WHERE FORCODE = '207';

UPDATE PAYFOR
SET SALETYPE = 'T'
WHERE FORCODE = '208';

UPDATE PAYFOR
SET SALETYPE = 'T'
WHERE FORCODE = '209';

UPDATE PAYFOR
SET SALETYPE = 'T'
WHERE FORCODE = '301';

UPDATE PAYFOR
SET SALETYPE = 'T'
WHERE FORCODE = '302';

UPDATE PAYFOR
SET SALETYPE = 'T'
WHERE FORCODE = '303';

UPDATE PAYFOR
SET SALETYPE = 'T'
WHERE FORCODE = '304';

UPDATE PAYFOR
SET SALETYPE = 'T'
WHERE FORCODE = '728';

UPDATE PAYFOR
SET SALETYPE = 'H'
WHERE FORCODE = '901';