ALTER TABLE CHQSTAT ALTER COLUMN BOOK SET DATA TYPE CHARACTER (15);
CALL SYSPROC.ADMIN_CMD ('REORG TABLE CHQSTAT');

/** ปิดเมนู ยกเลิกเช็คผ่าน, ยกเลิกเช็คคืน **/
UPDATE MAINMENU SET ACTIVE = 'N' WHERE MENUCODE = 'FIN205';
UPDATE MAINMENU SET ACTIVE = 'N' WHERE MENUCODE = 'FIN206';
UPDATE MAINMENU SET MENUNAME = 'ออกใบเสร็จรับเงินจองไฟแนนซ์' WHERE MENUCODE = 'FIN005';
UPDATE MAINMENU SET MENUNAME = 'บันทึกเงินโอนไม่ทราบที่มา' WHERE MENUCODE = 'FIN006';